# -*- coding: utf-8 -*-
"""Untitled38.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ovZI7f-p9sA07Sz_7jxbhwiIjHjdq0-q
"""

#"Write a program that prints the numbers from 1 to 100. But for multiples of three print “Fizz” instead of the number and for the multiples of five print “Buzz”. 
#For numbers which are multiples of both three and five print “FizzBuzz”."
for num in range(1,101):
    if num % 3 == 0 and num % 5 == 0:
        print("FizzBuzz: "+str(num))
    elif num % 3 == 0:
        print("Fizz:" +str(num))
    elif num % 5 == 0:
        print("Buzz:" +str(num))